### ISSUE TITLE
Annoyance: lexbox-api and fw-headless sometimes fail to connect to db on first try

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#1200]
When running `task up`, I sometimes encounter a sort of race condition where lexbox-api, and now also fw-headless, try to connect to the db, but end up connecting to the db container that's in the process of shutting down, rather than the db container that's about to be started up. This results in skaffold logs like the following:

```
[fw-headless] fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
[fw-headless]       An error occurred using the connection to database 'lexbox' on server 'tcp://db:5432'.
[fw-headless] fail: Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService[103]
[fw-headless]       Health check LexBoxDbContext with status Unhealthy completed after 1152.5157ms with message 'A task was canceled.'
[fw-headless]       System.Threading.Tasks.TaskCanceledException: A task was canceled.
[fw-headless]          at Npgsql.TaskTimeoutAndCancellation.ExecuteAsync(Func`2 getTaskFunc, NpgsqlTimeout timeout, CancellationToken cancellationToken)
[fw-headless]          at Npgsql.TaskTimeoutAndCancellation.ExecuteAsync[TResult](Func`2 getTaskFunc, NpgsqlTimeout timeout, CancellationToken cancellationToken)
[fw-headless]          at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
[fw-headless]          at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
[fw-headless]          at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|213_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
[fw-headless]          at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
[fw-headless]          at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
[fw-headless]          at Npgsql.PoolingDataSource.<Get>g__RentAsync|34_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
[fw-headless]          at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
[fw-headless]          at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
[fw-headless]          at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
[fw-headless]          at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
[fw-headless]          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
[fw-headless]          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
[fw-headless]          at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
[fw-headless]          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[fw-headless]          at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
[fw-headless]          at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
[fw-headless]          at LexData.LexBoxDbContext.HeathCheck(CancellationToken cancellationToken) in /src/backend/LexData/LexBoxDbContext.cs:line 38
[fw-headless]          at Microsoft.Extensions.Diagnostics.HealthChecks.DbContextHealthCheck`1.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
[lexbox-api] dotnet watch ⌚ Polling file watcher is enabled
[lexbox-api] dotnet watch 🚀 Started
[lexbox-api] Building...
[lexbox-api] fail: Quartz.Impl.AdoJobStore.MisfireHandler[0]
[lexbox-api]       Error handling misfires: Database error recovering from misfires.
[lexbox-api]       Quartz.JobPersistenceException: Database error recovering from misfires.
[lexbox-api]        ---> Npgsql.PostgresException (0x80004005): 57P01: terminating connection due to administrator command
[lexbox-api]          at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
[lexbox-api]          at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
[lexbox-api]          at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
[lexbox-api]          at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
[lexbox-api]          at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
[lexbox-api]          at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
[lexbox-api]          at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
[lexbox-api]          at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
[lexbox-api]          at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken)
[lexbox-api]          at Quartz.Impl.AdoJobStore.StdAdoDelegate.CountMisfiredTriggersInState(ConnectionAndTransactionHolder conn, String state1, DateTimeOffset ts, CancellationToken cancellationToken)
[lexbox-api]          at Quartz.Impl.AdoJobStore.JobStoreSupport.DoRecoverMisfires(Guid requestorId, CancellationToken cancellationToken)
[lexbox-api]         Exception data:
[lexbox-api]           Severity: FATAL
[lexbox-api]           SqlState: 57P01
[lexbox-api]           MessageText: terminating connection due to administrator command
[lexbox-api]           File: postgres.c
[lexbox-api]           Line: 3222
[lexbox-api]           Routine: ProcessInterrupts
```

If I edit a .cs file, skaffold syncs it to the lexbox-api and/or fw-headless container(s), and then `dotnet watch` picks up on the change and restarts the ASP.NET process — and then the backend API or FwHeadless containers start successfully because they can connect to the database. But it's a bit annoying to have to "kick" the backend into starting up just because of the timing of when it happened to try to connect to Postgres.

In discussion with Kevin, we discussed whether there might be another tool besides skaffold that we could use to sync files into the containers, and whether switching tools would help. Because we really don't need to re-deploy the DB container all the time the way skaffold does. We really only need the lexbox-api, ui, and fw-headless containers redeployed most of the time (and sometimes hgweb if we add a new command to command-runner.sh).

So we may want to investigate if there's a different tool that could do the container syncing for us, and then we'd just run `kubectl apply -k deployment/local-dev` to set up our build. If that would work, we might drop skaffold.

**Comment by hahn-kev** [comment]
closed by #1204
