### ISSUE TITLE
Can't create project running api locally

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#194]
When I try to create a new project in k8s locally, it doesn't seem to work and the result is always a 404 on the project page I'm redirected to:

```
fail: LexBoxApi.GraphQL.ErrorLoggingDiagnosticsEventListener[0]
      ResolverError: Unexpected Execution Error
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at LexBoxApi.Services.HgService.GetChangesets(String projectCode) in D:\code\languageforge-lexbox\backend\LexB
oxApi\Services\HgService.cs:line 67
         at LexCore.Entities.Project.GetChangesets(IHgService hgService) in D:\code\languageforge-lexbox\backend\LexCor
e\Entities\Project.cs:line 17
         at HotChocolate.Resolvers.Expressions.ExpressionHelper.AwaitTaskHelper[T](Task`1 task)
         at HotChocolate.Types.Helpers.FieldMiddlewareCompiler.<>c__DisplayClass9_0.<<CreateResolverMiddleware>b__0>d.M
oveNext()
      --- End of stack trace from previous location ---
         at DataAnnotatedModelValidations.ValidatorMiddleware.InvokeAsync(IMiddlewareContext context)
         at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
         at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancell
ationToken)
         at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
```

**Comment by myieye** [comment]
I realize now, I was actually running the api locally and everything else in k8s. If I run the api in k8s as well it works fine.

So, I assume what's happening here is that the actual repo is only on the local filesystem and so hg in k8s can't find it.

@hahn-kev @rmunn Is this something you've already thought through?

**Comment by hahn-kev** [comment]
Yeah you're right. It'll work correctly if it's in k8s, but changes to the local file system won't make it into the volume. I tried to get skaffold to sync the files into the right place but I couldn't get it to work for some reason.
