### ISSUE TITLE
Lots of failing request on fresh local deployment

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#313]
Lots of requests seem to fail on the first try after starting the app locally.

E.g. I think this is reproducable:

1) Starting the application locally (e.g. `task backend-up` + `task ui:o`) 
2) Wait until the cluster is ready
3) Go to http://127.0.0.1:3000/admin

💥 ===>
SvelteKit server logs: (there are ZERO logs shown in the skaffold output)
```
server-error-hook TypeError: fetch failed
    at fetch (D:\code\languageforge-lexbox\frontend\node_modules\.pnpm\undici@5.22.1\node_modules\un
dici\index.js:109:13)
    at async traceResponse (D:/code/languageforge-lexbox/frontend/src/lib/otel/otel.server.ts:67:20)
    at async eval (D:/code/languageforge-lexbox/frontend/src/lib/otel/otel.server.ts:81:14)
    at async Object.handleFetch (D:/code/languageforge-lexbox/frontend/src/hooks.server.ts:53:20)
    at async Object.eval [as fetch] (D:/code/languageforge-lexbox/frontend/node_modules/.pnpm/@svelt
ejs+kit@1.18.0_svelte@3.59.1_vite@4.4.9/node_modules/@sveltejs/kit/src/runtime/server/fetch.js:31:10
)
    at async load (D:/code/languageforge-lexbox/frontend/src/routes/+layout.server.ts:14:22)
    at async Module.load_server_data (D:/code/languageforge-lexbox/frontend/node_modules/.pnpm/@svel
tejs+kit@1.18.0_svelte@3.59.1_vite@4.4.9/node_modules/@sveltejs/kit/src/runtime/server/page/load_dat
a.js:57:17)
    at async eval (D:/code/languageforge-lexbox/frontend/node_modules/.pnpm/@sveltejs+kit@1.18.0_sve
lte@3.59.1_vite@4.4.9/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:150:13) {
  cause: SocketError: other side closed
      at Socket.onSocketEnd (D:\code\languageforge-lexbox\frontend\node_modules\.pnpm\undici@5.22.1\
node_modules\undici\lib\client.js:995:22)
      at Socket.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1358:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '127.0.0.1',
      localPort: 58251,
      remoteAddress: '127.0.0.1',
      remotePort: 5158,
      remoteFamily: 'IPv4',
      timeout: undefined,
      bytesWritten: 1078,
      bytesRead: 0
    }
  }
}
server-error-hook TypeError: fetch failed
    at fetch (D:\code\languageforge-lexbox\frontend\node_modules\.pnpm\undici@5.22.1\node_modules\un
dici\index.js:109:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async traceResponse (D:/code/languageforge-lexbox/frontend/src/lib/otel/otel.server.ts:67:20)
    at async eval (D:/code/languageforge-lexbox/frontend/src/lib/otel/otel.server.ts:81:14)
    at async Object.handleFetch (D:/code/languageforge-lexbox/frontend/src/hooks.server.ts:53:20)
    at async Object.eval [as fetch] (D:/code/languageforge-lexbox/frontend/node_modules/.pnpm/@svelt
ejs+kit@1.18.0_svelte@3.59.1_vite@4.4.9/node_modules/@sveltejs/kit/src/runtime/server/fetch.js:31:10
)
    at async load (D:/code/languageforge-lexbox/frontend/src/routes/+layout.server.ts:14:22)
    at async Module.load_server_data (D:/code/languageforge-lexbox/frontend/node_modules/.pnpm/@svel
tejs+kit@1.18.0_svelte@3.59.1_vite@4.4.9/node_modules/@sveltejs/kit/src/runtime/server/page/load_dat
a.js:57:17)
    at async eval (D:/code/languageforge-lexbox/frontend/node_modules/.pnpm/@sveltejs+kit@1.18.0_sve
lte@3.59.1_vite@4.4.9/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:150:13) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:5158
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 5158
  }
}
```

![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/67917910-4c88-4c66-b843-c868d5615496)

The trace ID in the screenshot (a6817b5c8828dc920804b84dd285c0a5) doesn't exist. Likely, because that request also failed 🤔. However, the otel-collector logs and honeycomb indicate that metrics are making it to the collector. That suggests that the issue only affects requests originating outside of the kubernetes cluster.

The things I can think of that might be relevant are:
- the ingress controller
- our vite proxy

**Comment by hahn-kev** [comment]
FYI the reason you don't see the error hitting localhost with up because that doesn't use the vite proxy at all, it uses ingress (just like production).

Thanks Tim, this is great documentation of the issue.

When do run `pnpm run dev` before or after you start up the backend without UI?
