### ISSUE TITLE
trapFocus not defined in dev

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#324]
![Image](https://github.com/sillsdev/languageforge-lexbox/assets/4575355/6d245098-0cc2-454c-acb8-4c2617596313)
https://ui.honeycomb.io/sil-language-forge/environments/test/trace/FyEYe8ZPVqH?fields[]=c_name&fields[]=c_service.name&fields[]=c_http.url&span=83d7e96849318021

during SSR
```
server-error-hook ReferenceError: trapFocus is not defined
    at Object.content (C:/dev/LexBox/frontend/src/lib/components/FilterBar/FilterBar.svelte:86:181)
    at eval (C:/dev/LexBox/frontend/src/lib/components/Dropdown.svelte:34:105)
    at Object.$$render (C:/dev/LexBox/frontend/node_modules/.pnpm/svelte@4.2.0/node_modules/svelte/src/runtime/internal/ssr.js:174:16)
    at eval (C:/dev/LexBox/frontend/src/lib/components/FilterBar/FilterBar.svelte:84:132)
    at Object.$$render (C:/dev/LexBox/frontend/node_modules/.pnpm/svelte@4.2.0/node_modules/svelte/src/runtime/internal/ssr.js:174:16)
    at eval (C:/dev/LexBox/frontend/src/routes/(authenticated)/admin/ProjectTable.svelte:146:308)
    at Object.$$render (C:/dev/LexBox/frontend/node_modules/.pnpm/svelte@4.2.0/node_modules/svelte/src/runtime/internal/ssr.js:174:16)
    at eval (C:/dev/LexBox/frontend/src/routes/(authenticated)/admin/+page.svelte:117:372)
    at Object.$$render (C:/dev/LexBox/frontend/node_modules/.pnpm/svelte@4.2.0/node_modules/svelte/src/runtime/internal/ssr.js:174:16)
    at Object.default (C:/dev/LexBox/frontend/.svelte-kit/generated/root.svelte:88:142)
    at Object.default (C:/dev/LexBox/frontend/src/routes/(authenticated)/+layout.svelte:64:43)
    at eval (C:/dev/LexBox/frontend/src/lib/layout/Content.svelte:8:108)
    at Object.$$render (C:/dev/LexBox/frontend/node_modules/.pnpm/svelte@4.2.0/node_modules/svelte/src/runtime/internal/ssr.js:174:16)
    at eval (C:/dev/LexBox/frontend/src/routes/(authenticated)/+layout.svelte:62:313)
    at Object.$$render (C:/dev/LexBox/frontend/node_modules/.pnpm/svelte@4.2.0/node_modules/svelte/src/runtime/internal/ssr.js:174:16)
    at Object.default (C:/dev/LexBox/frontend/.svelte-kit/generated/root.svelte:77:133)
    at eval (C:/dev/LexBox/frontend/src/routes/+layout.svelte:63:173)
    at Object.$$render (C:/dev/LexBox/frontend/node_modules/.pnpm/svelte@4.2.0/node_modules/svelte/src/runtime/internal/ssr.js:174:16)
    at eval (C:/dev/LexBox/frontend/.svelte-kit/generated/root.svelte:65:129)
    at $$render (C:/dev/LexBox/frontend/node_modules/.pnpm/svelte@4.2.0/node_modules/svelte/src/runtime/internal/ssr.js:174:16)
    at Object.render (C:/dev/LexBox/frontend/node_modules/.pnpm/svelte@4.2.0/node_modules/svelte/src/runtime/internal/ssr.js:182:17)
    at Module.render_response (C:/dev/LexBox/frontend/node_modules/.pnpm/@sveltejs+kit@1.24.1_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:185:29)
    at async Module.render_page (C:/dev/LexBox/frontend/node_modules/.pnpm/@sveltejs+kit@1.24.1_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:295:10)
    at async resolve (C:/dev/LexBox/frontend/node_modules/.pnpm/@sveltejs+kit@1.24.1_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/runtime/server/respond.js:415:18)
    at async traceResponse (C:/dev/LexBox/frontend/src/lib/otel/otel.server.ts:67:20)
    at async eval (C:/dev/LexBox/frontend/src/lib/otel/otel.server.ts:58:16)
    at async Module.respond (C:/dev/LexBox/frontend/node_modules/.pnpm/@sveltejs+kit@1.24.1_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/runtime/server/respond.js:282:20)      
    at async file:///C:/dev/LexBox/frontend/node_modules/.pnpm/@sveltejs+kit@1.24.1_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:505:22

```

**Comment by myieye** [comment]
I [removed all occurences of `trapFocus`](https://github.com/sillsdev/languageforge-lexbox/pull/273/commits/5873bf25f16397241e81a1d6c9b517135fa07a65#diff-679837056972b8a3b9dbfa5c7d56ed4197d27c87c7d2e8d28ed0019792176f73L67) in the Svelte 4 branch. I'm guessing your build just got a bit muddled up.

**Comment by hahn-kev** [comment]
you were right that was the issue.
