### ISSUE TITLE
Error: ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#460]
A few users have been getting the following error ([trace](https://ui.honeycomb.io/sil-language-forge/environments/prod/trace/qCrqvM66pWY?fields[]=s_name&fields[]=s_serviceName&span=c4b5fe00fb9b8442)):
![image001](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/6e45e440-a678-41fd-a143-b7b0ec582ea0)

I was able to debug it with one of them and tracked it to their LastPass extension (in Edge in this case). So, it's not really our problem.

```
web-client-content-script.js:2  DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at _s (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:125556)
    at Ou (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:138891)
    at t.unstable_runWithPriority (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:182589)
    at $o (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:83755)
    at Nu (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:136743)
    at vu (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:132867)
    at chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:84046
    at t.unstable_runWithPriority (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:182589)
    at $o (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:83755)
    at Jo (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:83991)
ss @ web-client-content-script.js:2
```

But we do have 3 problems:
1) For some reason the error message didn't make it on to the trace, so it was hard to find (it looks like the message we display is `event.message`, but we only trace `event.error`. So, that needs to change.)
2) We should include a stack trace. That will help us determine in the future if errors are coming from extensions or from our code.
3) How do we stop displaying meaningless errors like this one? Maybe we can just search for `chrome-extension://` in the stack trace and then maybe trace it, but not display it.

Hopefully we can install LastPass to reproduce this and then test and solve all 3 problems.

**Comment by myieye** [comment]
I copied the relevant info over
