### ISSUE TITLE
delete project failes during tests

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#486]
This issue shows up for the SendNewProject test

server logs: 
```
      => TraceId:be66dfd1be55d694a2810bb68a93e69a => ConnectionId:0HMVT8UTGD489 => RequestPath:/api/project/project/9b48e54b-0b3e-49ac-b333-ac021ef79bb9 RequestId:0HMVT8UTGD489:00000001
      Executed action LexBoxApi.Controllers.ProjectController.DeleteProject (LexBoxApi) in 149.3174ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      => TraceId:be66dfd1be55d694a2810bb68a93e69a => ConnectionId:0HMVT8UTGD489 => RequestPath:/api/project/project/9b48e54b-0b3e-49ac-b333-ac021ef79bb9 RequestId:0HMVT8UTGD489:00000001
      Executed endpoint 'LexBoxApi.Controllers.ProjectController.DeleteProject (LexBoxApi)'
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[2]
      => TraceId:be66dfd1be55d694a2810bb68a93e69a => ConnectionId:0HMVT8UTGD489 => RequestPath:/api/project/project/9b48e54b-0b3e-49ac-b333-ac021ef79bb9 RequestId:0HMVT8UTGD489:00000001
      Response:
      StatusCode: 200
      lexbox-version: v2023-12-15-fc398df8
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      => TraceId:be66dfd1be55d694a2810bb68a93e69a => ConnectionId:0HMVT8UTGD489 => RequestPath:/api/project/project/9b48e54b-0b3e-49ac-b333-ac021ef79bb9 RequestId:0HMVT8UTGD489:00000001
      An unhandled exception has occurred while executing the request.
      System.IO.IOException: Directory not empty : '/hg-repos/kevin-test-01/.hg/store/data'
         at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath)
         at LexBoxApi.Services.HgService.<>c__DisplayClass8_0.<DeleteRepo>b__0() in /LexBoxApi/Services/HgService.cs:line 77
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at LexBoxApi.Services.HgService.DeleteRepo(String code) in /LexBoxApi/Services/HgService.cs:line 77
         at LexBoxApi.Controllers.ProjectController.DeleteProject(Guid id) in /LexBoxApi/Controllers/ProjectController.cs:line 119
         at lambda_method1360(Closure, Object)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at LexSyncReverseProxy.ProxyKernel.<>c.<<UseResumableStatusHack>b__4_0>d.MoveNext() in /SyncReverseProxy/ProxyKernel.cs:line 143
      --- End of stack trace from previous location ---
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware.InvokeInternal(HttpContext context, HttpLoggingOptions options, HttpLoggingAttribute loggingAttribute, HttpLoggingFields loggingFields)
         at Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware.InvokeInternal(HttpContext context, HttpLoggingOptions options, HttpLoggingAttribute loggingAttribute, HttpLoggingFields loggingFields)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      => TraceId:be66dfd1be55d694a2810bb68a93e69a => ConnectionId:0HMVT8UTGD489 => RequestPath:/api/project/project/9b48e54b-0b3e-49ac-b333-ac021ef79bb9 RequestId:0HMVT8UTGD489:00000001
      Request finished HTTP/1.1 DELETE https://staging.languagedepot.org/api/project/project/9b48e54b-0b3e-49ac-b333-ac021ef79bb9 - 500 - application/problem+json;+charset=utf-8 154.4664ms
```

**Comment by myieye** [comment]
It seems to be the case that traces don't get exported when this happens. The trace [(be66dfd1be55d694a2810bb68a93e69a) doesn't exist](https://ui.honeycomb.io/sil-language-forge/environments/staging/trace?trace_id=be66dfd1be55d694a2810bb68a93e69a). I spent about an hour Yesterday trying to figure out why the DELETE trace wasn't in Honeycomb. I should have just looked in the server logs.

It's quite disappointing that an exception like this hasn't been making it into Honeycomb 😢. We need to fix that.

**Comment by myieye** [comment]
I just reproduced the 524 locally and it's as if the troublesome request never even makes it to our api. At least there are no logs.
There's a good one and then a huge gap and then the delete:
```
2023-12-15T14:52:11+01:00 info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
2023-12-15T14:52:11+01:00       => TraceId:43ed1b84a230cec868ce1dd116e32a83 => ConnectionId:0HMVTEB32G08D => RequestPath:/send-new-project-test-6076e761db994b48a4a92341b5b85607 RequestId:0HMVTEB32G08D:00000005
2023-12-15T14:52:11+01:00       Request finished HTTP/1.1 GET https://hg-staging.languageforge.org/send-new-project-test-6076e761db994b48a4a92341b5b85607?cmd=listkeys - 200 0 application/mercurial-0.1 881.8059ms
2023-12-15T14:56:37+01:00 info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
2023-12-15T14:56:37+01:00       => TraceId:44b48a8ef4c5d0d1e6568ced8f2d08ee => ConnectionId:0HMVTEB32G08E => RequestPath:/api/project/project/6076e761-db99-4b48-a4a9-2341b5b85607 RequestId:0HMVTEB32G08E:00000001
2023-12-15T14:56:37+01:00       Request starting HTTP/1.1 DELETE http://staging.languagedepot.org/api/project/project/6076e761-db99-4b48-a4a9-2341b5b85607 - - -
```
So, is it getting stuck at ingress? Should ingress be buffering differently?

**Comment by hahn-kev** [comment]
I like the idea of doing the delete out of band, I also think that my change to let us run the tests in parallel will mean that if one run fails to delete it won't make others fail.
