### ISSUE TITLE
Resumable issue pushing a new project

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#515]
An admin reported this issue. I grabbed the logs. The project code has been changed from the original.

<details>

```
10.42.5.13 - sdysart [23/Jan/2024:04:11:52 +0000] "GET /api/v03/getRevisions?offset=0&quantity=200&repoId=a-project-flex HTTP/1.1" 200 215 "-" "HgResume v03"
10.42.5.13 - sdysart [23/Jan/2024:04:12:02 +0000] "GET /api/v03/getRevisions?offset=0&quantity=200&repoId=a-project-flex HTTP/1.1" 200 215 "-" "HgResume v03"
10.42.5.13 - sdysart [23/Jan/2024:04:16:02 +0000] "POST /api/v03/pushBundleChunk?offset=0&chunkSize=5000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 290 "-" "HgResume v03"
10.42.5.13 - sdysart [23/Jan/2024:04:16:03 +0000] "POST /api/v03/pushBundleChunk?offset=5000&chunkSize=30755&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 291 "-" "HgResume v03"
10.42.5.13 - sdysart [23/Jan/2024:04:16:04 +0000] "POST /api/v03/pushBundleChunk?offset=35755&chunkSize=284392&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 292 "-" "HgResume v03"
10.42.5.13 - sdysart [23/Jan/2024:04:16:06 +0000] "POST /api/v03/pushBundleChunk?offset=320147&chunkSize=1521975&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 293 "-" "HgResume v03"
10.42.5.13 - sdysart [23/Jan/2024:04:16:09 +0000] "POST /api/v03/pushBundleChunk?offset=1842122&chunkSize=6410243&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 293 "-" "HgResume v03"
[Tue Jan 23 04:16:13.383351 2024] [php:warn] [pid 17] [client 10.42.5.13:43264] PHP Warning:  PHP Request Startup: POST Content-Length of 16008455 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:16:13 +0000] "POST /api/v03/pushBundleChunk?offset=8252365&chunkSize=16008455&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 294 "-" "HgResume v03"
[Tue Jan 23 04:16:19.090321 2024] [php:warn] [pid 18] [client 10.42.5.13:36340] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:16:19 +0000] "POST /api/v03/pushBundleChunk?offset=24260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 294 "-" "HgResume v03"
[Tue Jan 23 04:16:24.813786 2024] [php:warn] [pid 8281] [client 10.42.5.13:56818] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:16:24 +0000] "POST /api/v03/pushBundleChunk?offset=44260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 294 "-" "HgResume v03"
[Tue Jan 23 04:16:29.887216 2024] [php:warn] [pid 8281] [client 10.42.5.13:56818] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:16:29 +0000] "POST /api/v03/pushBundleChunk?offset=64260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 294 "-" "HgResume v03"
[Tue Jan 23 04:16:35.291737 2024] [php:warn] [pid 20] [client 10.42.5.13:35674] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:16:35 +0000] "POST /api/v03/pushBundleChunk?offset=84260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:16:40.380043 2024] [php:warn] [pid 20] [client 10.42.5.13:35674] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:16:40 +0000] "POST /api/v03/pushBundleChunk?offset=104260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:16:45.292261 2024] [php:warn] [pid 20] [client 10.42.5.13:35674] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:16:45 +0000] "POST /api/v03/pushBundleChunk?offset=124260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:16:50.270063 2024] [php:warn] [pid 20] [client 10.42.5.13:35674] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:16:50 +0000] "POST /api/v03/pushBundleChunk?offset=144260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:16:55.922727 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:16:55 +0000] "POST /api/v03/pushBundleChunk?offset=164260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:17:00.811541 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:17:00 +0000] "POST /api/v03/pushBundleChunk?offset=184260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:17:05.726704 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:17:05 +0000] "POST /api/v03/pushBundleChunk?offset=204260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:17:10.527256 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:17:10 +0000] "POST /api/v03/pushBundleChunk?offset=224260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:17:15.392993 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:17:15 +0000] "POST /api/v03/pushBundleChunk?offset=244260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:17:20.200364 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:17:20 +0000] "POST /api/v03/pushBundleChunk?offset=264260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:17:24.896959 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:17:24 +0000] "POST /api/v03/pushBundleChunk?offset=284260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:17:29.737367 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:17:29 +0000] "POST /api/v03/pushBundleChunk?offset=304260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:17:34.567975 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:17:34 +0000] "POST /api/v03/pushBundleChunk?offset=324260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:17:39.323459 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:17:39 +0000] "POST /api/v03/pushBundleChunk?offset=344260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:17:43.963753 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:17:43 +0000] "POST /api/v03/pushBundleChunk?offset=364260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:17:48.596587 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:17:48 +0000] "POST /api/v03/pushBundleChunk?offset=384260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:17:53.518912 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:17:53 +0000] "POST /api/v03/pushBundleChunk?offset=404260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:17:58.058339 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:17:58 +0000] "POST /api/v03/pushBundleChunk?offset=424260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:18:02.698793 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:18:02 +0000] "POST /api/v03/pushBundleChunk?offset=444260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:18:07.233030 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:18:07 +0000] "POST /api/v03/pushBundleChunk?offset=464260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:18:11.861793 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:18:11 +0000] "POST /api/v03/pushBundleChunk?offset=484260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:18:16.365465 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:18:16 +0000] "POST /api/v03/pushBundleChunk?offset=504260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:18:20.902800 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:18:20 +0000] "POST /api/v03/pushBundleChunk?offset=524260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:18:25.641573 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:18:25 +0000] "POST /api/v03/pushBundleChunk?offset=544260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:18:30.203240 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  PHP Request Startup: POST Content-Length of 20000000 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
10.42.5.13 - sdysart [23/Jan/2024:04:18:30 +0000] "POST /api/v03/pushBundleChunk?offset=564260820&chunkSize=20000000&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
[Tue Jan 23 04:18:31.385911 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  file_put_contents(/var/vcs/public/a-project-flex/hgRunner.log): Failed to open stream: Permission denied in /var/www/html/api/v03/src/HgRunner.php on line 39
[Tue Jan 23 04:18:31.387486 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  file_put_contents(/var/vcs/public/a-project-flex/hgRunner.log): Failed to open stream: Permission denied in /var/www/html/api/v03/src/HgRunner.php on line 41
[Tue Jan 23 04:19:03.373653 2024] [php:error] [pid 21] [client 10.42.5.13:41682] PHP Fatal error:  Uncaught AsyncRunnerException: Lock file '/var/cache/hgresume/65c1c18b-f7c3-4aaf-bd8d-a8157851d072.bundle.async_run' not found, process is not running in /var/www/html/api/v03/src/AsyncRunner.php:39\nStack trace:\n#0 /var/www/html/api/v03/src/HgResumeApi.php(139): AsyncRunner->isComplete()\n#1 /var/www/html/api/v03/src/RestServer.php(38): HgResumeAPI->pushBundleChunk()\n#2 /var/www/html/api/v03/index.php(22): RestServer->handle()\n#3 {main}\n  thrown in /var/www/html/api/v03/src/AsyncRunner.php on line 39
10.42.5.13 - sdysart [23/Jan/2024:04:19:03 +0000] "POST /api/v03/pushBundleChunk?offset=584260820&chunkSize=944735&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 500 210 "-" "HgResume v03"
[Tue Jan 23 04:19:04.569038 2024] [php:error] [pid 26] [client 10.42.5.13:41688] PHP Fatal error:  Uncaught AsyncRunnerException: Lock file '/var/cache/hgresume/65c1c18b-f7c3-4aaf-bd8d-a8157851d072.bundle.async_run' not found, process is not running in /var/www/html/api/v03/src/AsyncRunner.php:39\nStack trace:\n#0 /var/www/html/api/v03/src/HgResumeApi.php(139): AsyncRunner->isComplete()\n#1 /var/www/html/api/v03/src/RestServer.php(38): HgResumeAPI->pushBundleChunk()\n#2 /var/www/html/api/v03/index.php(22): RestServer->handle()\n#3 {main}\n  thrown in /var/www/html/api/v03/src/AsyncRunner.php on line 39
10.42.5.13 - sdysart [23/Jan/2024:04:19:04 +0000] "POST /api/v03/pushBundleChunk?offset=584260820&chunkSize=944735&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 500 210 "-" "HgResume v03"
[Tue Jan 23 04:19:05.730890 2024] [php:error] [pid 17] [client 10.42.5.13:41700] PHP Fatal error:  Uncaught AsyncRunnerException: Lock file '/var/cache/hgresume/65c1c18b-f7c3-4aaf-bd8d-a8157851d072.bundle.async_run' not found, process is not running in /var/www/html/api/v03/src/AsyncRunner.php:39\nStack trace:\n#0 /var/www/html/api/v03/src/HgResumeApi.php(139): AsyncRunner->isComplete()\n#1 /var/www/html/api/v03/src/RestServer.php(38): HgResumeAPI->pushBundleChunk()\n#2 /var/www/html/api/v03/index.php(22): RestServer->handle()\n#3 {main}\n  thrown in /var/www/html/api/v03/src/AsyncRunner.php on line 39
10.42.5.13 - sdysart [23/Jan/2024:04:19:05 +0000] "POST /api/v03/pushBundleChunk?offset=584260820&chunkSize=944735&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 500 210 "-" "HgResume v03"
[Tue Jan 23 04:19:06.898626 2024] [php:error] [pid 18] [client 10.42.5.13:41712] PHP Fatal error:  Uncaught AsyncRunnerException: Lock file '/var/cache/hgresume/65c1c18b-f7c3-4aaf-bd8d-a8157851d072.bundle.async_run' not found, process is not running in /var/www/html/api/v03/src/AsyncRunner.php:39\nStack trace:\n#0 /var/www/html/api/v03/src/HgResumeApi.php(139): AsyncRunner->isComplete()\n#1 /var/www/html/api/v03/src/RestServer.php(38): HgResumeAPI->pushBundleChunk()\n#2 /var/www/html/api/v03/index.php(22): RestServer->handle()\n#3 {main}\n  thrown in /var/www/html/api/v03/src/AsyncRunner.php on line 39
10.42.5.13 - sdysart [23/Jan/2024:04:19:06 +0000] "POST /api/v03/pushBundleChunk?offset=584260820&chunkSize=944735&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 500 210 "-" "HgResume v03"
[Tue Jan 23 04:19:08.079544 2024] [php:error] [pid 8281] [client 10.42.5.13:41722] PHP Fatal error:  Uncaught AsyncRunnerException: Lock file '/var/cache/hgresume/65c1c18b-f7c3-4aaf-bd8d-a8157851d072.bundle.async_run' not found, process is not running in /var/www/html/api/v03/src/AsyncRunner.php:39\nStack trace:\n#0 /var/www/html/api/v03/src/HgResumeApi.php(139): AsyncRunner->isComplete()\n#1 /var/www/html/api/v03/src/RestServer.php(38): HgResumeAPI->pushBundleChunk()\n#2 /var/www/html/api/v03/index.php(22): RestServer->handle()\n#3 {main}\n  thrown in /var/www/html/api/v03/src/AsyncRunner.php on line 39
10.42.5.13 - sdysart [23/Jan/2024:04:19:08 +0000] "POST /api/v03/pushBundleChunk?offset=584260820&chunkSize=944735&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 500 210 "-" "HgResume v03"
[Tue Jan 23 04:19:09.285439 2024] [php:error] [pid 20] [client 10.42.5.13:41728] PHP Fatal error:  Uncaught AsyncRunnerException: Lock file '/var/cache/hgresume/65c1c18b-f7c3-4aaf-bd8d-a8157851d072.bundle.async_run' not found, process is not running in /var/www/html/api/v03/src/AsyncRunner.php:39\nStack trace:\n#0 /var/www/html/api/v03/src/HgResumeApi.php(139): AsyncRunner->isComplete()\n#1 /var/www/html/api/v03/src/RestServer.php(38): HgResumeAPI->pushBundleChunk()\n#2 /var/www/html/api/v03/index.php(22): RestServer->handle()\n#3 {main}\n  thrown in /var/www/html/api/v03/src/AsyncRunner.php on line 39
10.42.5.13 - sdysart [23/Jan/2024:04:19:09 +0000] "POST /api/v03/pushBundleChunk?offset=584260820&chunkSize=944735&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 500 210 "-" "HgResume v03"
[Tue Jan 23 04:19:10.408930 2024] [php:error] [pid 21] [client 10.42.5.13:41732] PHP Fatal error:  Uncaught AsyncRunnerException: Lock file '/var/cache/hgresume/65c1c18b-f7c3-4aaf-bd8d-a8157851d072.bundle.async_run' not found, process is not running in /var/www/html/api/v03/src/AsyncRunner.php:39\nStack trace:\n#0 /var/www/html/api/v03/src/HgResumeApi.php(139): AsyncRunner->isComplete()\n#1 /var/www/html/api/v03/src/RestServer.php(38): HgResumeAPI->pushBundleChunk()\n#2 /var/www/html/api/v03/index.php(22): RestServer->handle()\n#3 {main}\n  thrown in /var/www/html/api/v03/src/AsyncRunner.php on line 39
10.42.5.13 - sdysart [23/Jan/2024:04:19:10 +0000] "POST /api/v03/pushBundleChunk?offset=584260820&chunkSize=944735&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 500 210 "-" "HgResume v03"
[Tue Jan 23 04:19:11.531461 2024] [php:error] [pid 26] [client 10.42.5.13:49148] PHP Fatal error:  Uncaught AsyncRunnerException: Lock file '/var/cache/hgresume/65c1c18b-f7c3-4aaf-bd8d-a8157851d072.bundle.async_run' not found, process is not running in /var/www/html/api/v03/src/AsyncRunner.php:39\nStack trace:\n#0 /var/www/html/api/v03/src/HgResumeApi.php(139): AsyncRunner->isComplete()\n#1 /var/www/html/api/v03/src/RestServer.php(38): HgResumeAPI->pushBundleChunk()\n#2 /var/www/html/api/v03/index.php(22): RestServer->handle()\n#3 {main}\n  thrown in /var/www/html/api/v03/src/AsyncRunner.php on line 39
10.42.5.13 - sdysart [23/Jan/2024:04:19:11 +0000] "POST /api/v03/pushBundleChunk?offset=584260820&chunkSize=944735&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 500 210 "-" "HgResume v03"
[Tue Jan 23 04:19:12.650744 2024] [php:error] [pid 17] [client 10.42.5.13:49164] PHP Fatal error:  Uncaught AsyncRunnerException: Lock file '/var/cache/hgresume/65c1c18b-f7c3-4aaf-bd8d-a8157851d072.bundle.async_run' not found, process is not running in /var/www/html/api/v03/src/AsyncRunner.php:39\nStack trace:\n#0 /var/www/html/api/v03/src/HgResumeApi.php(139): AsyncRunner->isComplete()\n#1 /var/www/html/api/v03/src/RestServer.php(38): HgResumeAPI->pushBundleChunk()\n#2 /var/www/html/api/v03/index.php(22): RestServer->handle()\n#3 {main}\n  thrown in /var/www/html/api/v03/src/AsyncRunner.php on line 39
10.42.5.13 - sdysart [23/Jan/2024:04:19:12 +0000] "POST /api/v03/pushBundleChunk?offset=584260820&chunkSize=944735&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 500 210 "-" "HgResume v03"
[Tue Jan 23 04:19:13.815081 2024] [php:error] [pid 18] [client 10.42.5.13:49176] PHP Fatal error:  Uncaught AsyncRunnerException: Lock file '/var/cache/hgresume/65c1c18b-f7c3-4aaf-bd8d-a8157851d072.bundle.async_run' not found, process is not running in /var/www/html/api/v03/src/AsyncRunner.php:39\nStack trace:\n#0 /var/www/html/api/v03/src/HgResumeApi.php(139): AsyncRunner->isComplete()\n#1 /var/www/html/api/v03/src/RestServer.php(38): HgResumeAPI->pushBundleChunk()\n#2 /var/www/html/api/v03/index.php(22): RestServer->handle()\n#3 {main}\n  thrown in /var/www/html/api/v03/src/AsyncRunner.php on line 39
10.42.5.13 - sdysart [23/Jan/2024:04:19:13 +0000] "POST /api/v03/pushBundleChunk?offset=584260820&chunkSize=944735&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 500 210 "-" "HgResume v03"
[Tue Jan 23 04:19:14.961113 2024] [php:error] [pid 8281] [client 10.42.5.13:49190] PHP Fatal error:  Uncaught AsyncRunnerException: Lock file '/var/cache/hgresume/65c1c18b-f7c3-4aaf-bd8d-a8157851d072.bundle.async_run' not found, process is not running in /var/www/html/api/v03/src/AsyncRunner.php:39\nStack trace:\n#0 /var/www/html/api/v03/src/HgResumeApi.php(139): AsyncRunner->isComplete()\n#1 /var/www/html/api/v03/src/RestServer.php(38): HgResumeAPI->pushBundleChunk()\n#2 /var/www/html/api/v03/index.php(22): RestServer->handle()\n#3 {main}\n  thrown in /var/www/html/api/v03/src/AsyncRunner.php on line 39
10.42.5.13 - sdysart [23/Jan/2024:04:19:14 +0000] "POST /api/v03/pushBundleChunk?offset=584260820&chunkSize=944735&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 500 210 "-" "HgResume v03"
[Tue Jan 23 04:19:15.912806 2024] [php:warn] [pid 19] [client 10.42.5.13:40218] PHP Warning:  file_put_contents(/var/vcs/public/a-project-flex/hgRunner.log): Failed to open stream: Permission denied in /var/www/html/api/v03/src/HgRunner.php on line 41
10.42.5.13 - sdysart [23/Jan/2024:04:19:16 +0000] "POST /api/v03/pushBundleChunk?offset=584260820&chunkSize=944735&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"
10.42.5.13 - sdysart [23/Jan/2024:04:18:31 +0000] "POST /api/v03/pushBundleChunk?offset=584260820&chunkSize=944735&bundleSize=585205555&transId=65c1c18b-f7c3-4aaf-bd8d-a8157851d072&repoId=a-project-flex HTTP/1.1" 202 295 "-" "HgResume v03"

```
</details>

everything seems to be going fine (though there's warnings about php content length limits), until `04:18:31.385911` and then there's a permission issue opening hgRunner.log in the repo. After that the session fails until the client gives up.

This is an intermitent issue. The user was able to send the project again later and it worked fine.

**Comment by rmunn** [comment]
One thing that might be causing permissions issues is that the project directories in /var/vcs/public are all owned by root with group owner www-data, and mode rwxr-x---. Meaning that the Apache process running as www-data cannot create new files (such as `hgRunner.log`) in that directory.

If we can get the process creating those directories to run as umask 002 rather than 022, so that it doesn't strip the group-writable bit, then www-data would be able to modify hgRunner.log. Alternately, we could set file permissions on the directories after creating them. The appropriate permissions are already set on the .hg folder inside: rwsrws---; the group "sticky bit" on the directory ensures that the appropriate group ownership will be created on files under that directory. But when we create a new project, we need to ensure that the top-level directory also gets the rwsrws--- permissions applied, so that PHP will be able to create a new hgRunner.log file in there.

**Comment by rmunn** [comment]
Correction: the two s's in the permissions are the "set user ID" and "set group ID" bits, respectively. The sticky bit, which is usually set on temp directories, shows as a `t` in the third group of bits, e.g. the permissions for /tmp are usually rwxrwxrwt.

The chmod command for setting rwsrws--- permissions is `chmod 6770 dirname`, or alternately `chmod u=rwxs,g=rwxs,o= dirname`.

**Comment by myieye** [comment]
After testing this I created a new issue for resumable: https://github.com/sillsdev/hgresume/issues/10
Other than that bug, it seems to be working.
So, I _think_ that Lexbox is okay now 😆
