### ISSUE TITLE
FW Lite developer readme and housekeeping

### ISSUE THREAD

**Issue by megahirt** [sillsdev/languageforge-lexbox#927]

**Comment by hahn-kev** [comment]
@psh0078 would you take a look at this? Try to run FW Lite locally on your machine (I'd also like to test it out on Mac). And provide feedback on where the current readme is lacking.

**Comment by psh0078** [comment]
```
[fw-lite:local-web-app-for-develop] info: LocalWebApp[0]
[fw-lite:local-web-app-for-develop]       FwLite LocalWebApp startup
[fw-lite:local-web-app-for-develop] Unhandled exception. System.InvalidOperationException: Could not load the embedded file manifest 'Microsoft.Extensions.FileProviders.Embedded.Manifest.xml' for assembly 'LocalWebApp'.
[fw-lite:local-web-app-for-develop]    at Microsoft.Extensions.FileProviders.Embedded.Manifest.ManifestParser.Parse(Assembly assembly, String name)
[fw-lite:local-web-app-for-develop]    at Microsoft.Extensions.FileProviders.ManifestEmbeddedFileProvider..ctor(Assembly assembly)
[fw-lite:local-web-app-for-develop]    at LocalWebApp.LocalWebAppServer.SetupAppServer(String[] args, Action`1 configure) in C:\Users\seongho\Desktop\languageforge-lexbox\backend\FwLite\LocalWebApp\LocalWebAppServer.cs:line 55
[fw-lite:local-web-app-for-develop]    at Program.<Main>$(String[] args) in C:\Users\seongho\Desktop\languageforge-lexbox\backend\FwLite\LocalWebApp\Program.cs:line 4
[fw-lite:local-web-app-for-develop]    at Program.<Main>(String[] args)
[fw-lite:local-web-app-for-develop] dotnet watch ❌ Exited with error code -532462766
[fw-lite:local-web-app-for-develop] dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
```

**Comment by psh0078** [comment]
Running on a Mac: it complains that ICU library can't be loaded.
```
[local-web-app-for-develop] Unhandled exception. System.IO.FileLoadException: Can't load ICU library (version 0)
[local-web-app-for-develop] File name: 'icuuc'
[local-web-app-for-develop]    at Icu.NativeMethods.LoadIcuLibrary(String libraryName)
[local-web-app-for-develop]    at Icu.NativeMethods.get_IcuCommonLibHandle()
[local-web-app-for-develop]    at Icu.NativeMethods.u_init(ErrorCode& errorCode)
[local-web-app-for-develop]    at Icu.Wrapper.Init()
[local-web-app-for-develop]    at FwDataMiniLcmBridge.LcmUtils.ProjectLoader.Init() in /Users/kafka/Dev/languageforge-lexbox/backend/FwLite/FwDataMiniLcmBridge/LcmUtils/ProjectLoader.cs:line 30
[local-web-app-for-develop]    at LocalWebApp.LocalWebAppServer.SetupAppServer(String[] args, Action`1 configure) in /Users/kafka/Dev/languageforge-lexbox/backend/FwLite/LocalWebApp/LocalWebAppServer.cs:line 25
[local-web-app-for-develop]    at Program.<Main>$(String[] args) in /Users/kafka/Dev/languageforge-lexbox/backend/FwLite/LocalWebApp/Program.cs:line 4
[local-web-app-for-develop]    at Program.<Main>(String[] args)
[local-web-app-for-develop] dotnet watch ❌ Exited with error code 134
[local-web-app-for-develop] dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
```
